### ISSUE TITLE
fails to compile under archlinux

### ISSUE THREAD

**Issue by xradiation** [nowsecure/r2frida#223]
installing `r2frida` using `r2pm -ci r2frida` failed unable to find nodejs modules as the error suggests, 

-error log: [r2frida_install_log](https://mega.nz/file/L6YRhYia#PrwKCXAc5JdepmVOoNMq1Qpn3T1TWarLmFk9FHAYBDc)
-the .npm [log](https://mega.nz/file/u7ICDAQa#HrjqiNAocTiDyPp6e2u6KJSD8fFcJaKElMyUY3W7TnU)
and btw no need to download, just click on 'note' icone on the top.

**Comment by xradiation** [comment]
Downgrading to an earlier version of nodejs fixed the issue : specifically `nodejs-13.2.0-1`, however the issue still up.

**Comment by trufae** [comment]
i think this issue belongs to frida-compile, not r2frida. @oleavr can you take a look at this?

```
$ npm i

> r2frida-agent@4.3.0 prepare /Users/pancake/ns/r2frida
> npm run build


> r2frida-agent@4.3.0 build /Users/pancake/ns/r2frida
> frida-compile -L -c src/agent -o src/_agent.js

Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/pancake/ns/r2frida/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/pancake/ns/r2frida/node_modules/@babel/preset-env/lib/index.js
- /Users/pancake/ns/r2frida/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/pancake/ns/r2frida/node_modules/@babel/core/lib/config/files/index.js
- /Users/pancake/ns/r2frida/node_modules/@babel/core/lib/index.js
- /Users/pancake/ns/r2frida/node_modules/babelify/index.js
- /Users/pancake/ns/r2frida/node_modules/frida-compile/index.js
- /Users/pancake/ns/r2frida/node_modules/frida-compile/bin/compile.js while parsing file: /Users/pancake/ns/r2frida/src/agent/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/pancake/ns/r2frida/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pancake/ns/r2frida/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js',
    '/Users/pancake/ns/r2frida/node_modules/@babel/preset-env/lib/index.js',
    '/Users/pancake/ns/r2frida/node_modules/@babel/core/lib/config/files/plugins.js',
    '/Users/pancake/ns/r2frida/node_modules/@babel/core/lib/config/files/index.js',
    '/Users/pancake/ns/r2frida/node_modules/@babel/core/lib/index.js',
    '/Users/pancake/ns/r2frida/node_modules/babelify/index.js',
    '/Users/pancake/ns/r2frida/node_modules/frida-compile/index.js',
    '/Users/pancake/ns/r2frida/node_modules/frida-compile/bin/compile.js'
  ],
  filename: '/Users/pancake/ns/r2frida/src/agent/index.js',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      error: [Function (anonymous)],
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [Deps], [DestroyableTransform] ],
    length: 2,
    label: 'deps',
    [Symbol(kCapture)]: false
  },
  inputs: Set(7) {
    '/Users/pancake/ns/r2frida/src/agent/index.js',
    '/Users/pancake/ns/r2frida/node_modules/typescript/lib/lib.d.ts',
    '/Users/pancake/ns/r2frida/node_modules/typescript/lib/lib.es5.d.ts',
    '/Users/pancake/ns/r2frida/node_modules/typescript/lib/lib.dom.d.ts',
    '/Users/pancake/ns/r2frida/node_modules/typescript/lib/lib.webworker.importscripts.d.ts',
    '/Users/pancake/ns/r2frida/node_modules/typescript/lib/lib.scripthost.d.ts',
    '/Users/pancake/ns/r2frida/package.json'
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r2frida-agent@4.3.0 build: `frida-compile -L -c src/agent -o src/_agent.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r2frida-agent@4.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pancake/.npm/_logs/2020-04-20T16_25_57_721Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r2frida-agent@4.3.0 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r2frida-agent@4.3.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pancake/.npm/_logs/2020-04-20T16_25_57_793Z-debug.log
```

**Comment by trufae** [comment]
confirmed the issue is not in r2frida, but in frida-compile. I've reported that to @oleavr and i'll come back with an update here when this gets ready.

Can you use node12 meanwhile?

**Comment by xradiation** [comment]
hi @trufae ;
as i mentioned above (perhaps not as clearly as i shoud "edited now"), i downgraded to `13.2.0-1` and that fixed the issue.
Best Regards
