### ISSUE TITLE
下载非常慢怎么提高速度

### ISSUE THREAD

**Issue by liumengdeqq** [nowsecure/r2frida#225]
curl -Ls https://github.com/frida/frida/releases/download/12.8.20/frida-core-devkit-12.8.20-macos-x86_64.tar.xz | xz -d | tar -C ext/frida-macos-12.8.20/_ -xf - 下载非常慢

**Comment by 18345093167** [comment]
下载非常慢

**Comment by radare** [comment]
It will be slower to compile frida than to download the precompiled sdk

**Comment by trufae** [comment]
i've tracked down the issue to get the frida reproducer. The crash happens when trying to read 4 bytes at address 8, you can get the same crash like this:

```
$ frida -U -p $pidof.com.android.chrome
-> Memory.readByteArray(ptr(8), 4)
```

So it's an issue in frida server's Exceptor for android/thumb.

From the r2frida side i did a workaround that is now available on master. Run r2 like this:

```
R2FRIDA_SAFE_IO=1 r2 frida://usb//pid
```

**Comment by trufae** [comment]
The SDK is cached after the first download. do you want an env var or something to specify a different location fro the SDK to download it from a local server or so? that may be an option to fix this issue

**Comment by 18345093167** [comment]
I have tried changed /etc/hosts as following and it works fine.
127.0.0.1       localhost
127.0.1.1       burning-RedmiBook-14-APCS

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.30.253.113          github.com
151.101.185.194         github.global.ssl.fastly.net

**Comment by radare** [comment]
You need root for this, but yeah i can set that hostname in a variablr that you can override to fetch the frida sdk from a different source

**Comment by 18345093167** [comment]
It wastes lots of time to download frida. Could you please add code to check whether there is frida on corresponding device?

**Comment by trufae** [comment]
This is the frida sdk. It is needed to build r2frida. It have nothing to do with the device.

**Comment by BurningTeng** [comment]
Thanks very much.

Could you please help to see following error. I use command `r2pm -i r2frida` to install r2frida since frida is updated recently. But following error occur. Is it related rida-core-devkit-14.1.2-linux-x86_64.tar.xz?
```
curl -Ls https://github.com/frida/frida/releases/download/14.1.2/frida-core-devkit-14.1.2-linux-x86_64.tar.xz | xz -d | tar -C ext/frida-linux-14.1.2/_ -xf -
mv ext/frida-linux-14.1.2/_/* ext/frida-linux-14.1.2
rmdir ext/frida-linux-14.1.2/_
#mv ext/frida ext/frida-linux-14.1.2
cd ext && ln -fs frida-linux-14.1.2 frida
[ "`readlink ext/frida`" = frida-linux-14.1.2 ] || \
	(cd ext && rm -f frida ; ln -fs frida-linux-14.1.2 frida)
make io_frida.so
make[1]: 进入目录“/home/burning/.local/share/radare2/r2pm/git/r2frida”
mkdir -p node_modules
npm i

> frida@14.1.2 install /home/burning/.local/share/radare2/r2pm/git/r2frida/node_modules/frida
> prebuild-install || node-gyp rebuild

prebuild-install WARN install unexpected end of file
Traceback (most recent call last):
  File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-56-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/burning/.local/share/radare2/r2pm/git/r2frida/node_modules/frida
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frida@14.1.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frida@14.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/burning/.npm/_logs/2020-12-07T04_22_25_558Z-debug.log
make[1]: *** [Makefile:160：node_modules] 错误 1
make[1]: 离开目录“/home/burning/.local/share/radare2/r2pm/git/r2frida”
make: *** [Makefile:99：all] 错误 2
ERROR: Build failed

```

**Comment by trufae** [comment]
Try with r2pm -ci r2frida ( note the extra -c )

**Comment by BurningTeng** [comment]
Sorry. My spelling is error. I use command `r2pm -ci r2frida`. Result is same as above.

**Comment by trufae** [comment]
Seems like there's a problem in `pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application` can you check if this pip pkg is installed properly?

**Comment by BurningTeng** [comment]
Could you please tell me the node version of your build?

**Comment by BurningTeng** [comment]
It seems node-gpy problem. I tried node 14 to rebuild.

**Comment by oleavr** [comment]
@BurningTeng It's a network/firewall-issue:

> prebuild-install WARN install unexpected end of file

The errors following that should be ignored, as frida-node doesn't yet supported being built from source out-of-tree, it relies on downloading prebuilds. (We currently provide prebuilds for Node.js 10, 12, and 14.)

**Comment by BurningTeng** [comment]
Thanks.

I use latest stable nodejs 14. I can install it by  r2 -i r2frida
